from django.conf.urls.defaults import *

urlpatterns = patterns('',
    url(r'^$',
        'siteapps_v1.bible_tidbits.views.home',
        name='home'
    ),
    url(r'^mine/$',
        'siteapps_v1.bible_tidbits.views.my_tidbits',
        name='my-tidbits'
    ),
    url(r'^questions/$',
        'siteapps_v1.bible_tidbits.views.question_tidbits',
        name='question-tidbits'
    ),
    url(r'^user/(?P<username>[\w]+)/$',
        'siteapps_v1.bible_tidbits.views.tidbits_by_user',
        name='tidbits-by-user'
    ),
    url(r'^add/$',
        'siteapps_v1.bible_tidbits.views.add',
        name='add'
    ),
    url(r'^(?P<book>(\d-)?[\w-]+)/$',
        'siteapps_v1.bible_tidbits.views.tidbits_by_book',
        name='tidbits-by-book'
    ),
    url(r'^tags/(?P<tag_slug>[\w-]+)/$',
        'siteapps_v1.bible_tidbits.views.tidbits_by_tag',
        name='tidbits-by-tag'
    ),
    url(r'^edit/(?P<tidbit_id>\d+)/$',
        'siteapps_v1.bible_tidbits.views.edit',
        name='edit'
    ),
    url(r'^delete/(?P<tidbit_id>\d+)/$',
        'siteapps_v1.bible_tidbits.views.delete',
        name='delete'
    ),
    url(r'^ajax/tags/$',
        'siteapps_v1.bible_tidbits.views.ajax_tags',
    ),
    url(r'^ajax/bible_text/$',
        'siteapps_v1.bible_tidbits.views.ajax_bible_text',
    ),
)
